Add colored inventory tags
hex-agon/mastering-mixology pull request #78
Opened 2024-10-16 15:14 UTC by whiitehead

- Options to change inventory tag type
- Colored inventory tags
- Applies tags to modified potions now

<img width="243" alt="Screenshot 2024-10-16 at 7 42 19 AM" src="https://github.com/user-attachments/assets/33fce015-b996-4fd0-8f95-5a51045cb11f">

2024-10-16 16:52 UTC, raiyni requested changes

2024-10-16 16:52 UTC, raiyni commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +    private static final int MODIFIED_POTION_ID_DIFF = ItemID.MIXALOT_30030 - ItemID.MIXALOT;
Don't do this as it's generally not kosher to rely on the order of itemid. Probably should add a ctor parameter to potion type and they can be added to the same item map.

2024-10-16 16:52 UTC, raiyni commented on src/main/java/work/fking/masteringmixology/MasteringMixologyConfig.java
> +    default InventoryPotionTagType inventoryPotionTagType() {
Reuse the current config defaulted to white

2024-10-16 16:52 UTC, raiyni commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +        drawRecipe(graphics2D, potion, 1, 13, Color.BLACK); // Drop shadow
Personally don't like the shadow, it should at least be configurable

2024-10-16 16:52 UTC, raiyni commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +        // Font measurements come from: graphics2D.getFontMetrics(FontManager.getRunescapeSmallFont())
Use the measurements call instead of hard coding numbers

2024-10-16 16:52 UTC, raiyni commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +            if (component == MOX) {
You don't need to do all of this casing if you just use the measurement and use the component.character() and component.color()

2024-10-16 16:52 UTC, raiyni commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +            imageCache.put(potion, createRecipeImage(potion));
caching these is unnecessary, just draw the text

2024-10-16 16:52 UTC, raiyni commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +        var image = new BufferedImage(25, 13, BufferedImage.TYPE_INT_ARGB);
no need to make a new buffered image

2024-10-16 16:52 UTC, raiyni commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +        if (config.inventoryPotionTagType() == InventoryPotionTagType.COLORED) {
this can be removed if the draw function determines the color

2024-10-16 16:52 UTC, raiyni commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +        if (color != null) {
this can be removed

2024-10-16 16:52 UTC, raiyni commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +        var potion = PotionType.fromItemId(itemId <= ItemID.MIXALOT ? itemId : itemId - MODIFIED_POTION_ID_DIFF);
undo this

2024-10-16 16:52 UTC, raiyni commented on src/main/java/work/fking/masteringmixology/MasteringMixologyPlugin.java
> +        if (event.getKey().equals("inventoryPotionTags")) {
remove this

2024-10-16 17:01 UTC, whiitehead commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +        drawRecipe(graphics2D, potion, 1, 13, Color.BLACK); // Drop shadow
Then should I make the shadow on resin configurable. What about the shadow on the overlay. Everything has shadow. I'm not making it configurable.

2024-10-16 17:38 UTC, raiyni commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +        drawRecipe(graphics2D, potion, 1, 13, Color.BLACK); // Drop shadow
You are making a false equivalence about how things are rendered. The rendering engine for widgets isn't the same as the rendering engine for Runelite overlays.

If you really wanted to be in the spirit of runelite, you would do rendering like the Item Identification plugin. I believe that might have a shadow in TextComponent it handles and even parses colors.

2024-10-16 17:55 UTC, whiitehead commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +        drawRecipe(graphics2D, potion, 1, 13, Color.BLACK); // Drop shadow
> Personally don't like the shadow

It's not a false equivalent. You are commenting on what the user sees. The user doesn't see implementation details. The spirit of RuneLite is to add a drop shadow. If you know of a better way of doing it I'm happy to change it.

2024-10-16 17:55 UTC, whiitehead commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +        var potion = PotionType.fromItemId(itemId <= ItemID.MIXALOT ? itemId : itemId - MODIFIED_POTION_ID_DIFF);
You already commented on this here: https://github.com/hex-agon/mastering-mixology/pull/78#discussion_r1803457126

You don't need to comment again.

2024-10-16 17:57 UTC, whiitehead commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +        var image = new BufferedImage(25, 13, BufferedImage.TYPE_INT_ARGB);
If I don't make a new BufferedImage then the caching doesn't work. You have already said your piece about the caching system. You don't need to do it again.

2024-10-16 17:58 UTC, whiitehead commented on src/main/java/work/fking/masteringmixology/MasteringMixologyPlugin.java
> +        if (event.getKey().equals("inventoryPotionTags")) {
https://github.com/hex-agon/mastering-mixology/pull/78#discussion_r1803471906

2024-10-16 18:05 UTC, whiitehead commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +            if (component == MOX) {
You don't need to comment the same recommendation 5 times. This is a good idea and I will have a revision coming.

2024-10-16 18:05 UTC, whiitehead commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +        // Font measurements come from: graphics2D.getFontMetrics(FontManager.getRunescapeSmallFont())
https://github.com/hex-agon/mastering-mixology/pull/78#discussion_r1803469136

2024-10-16 19:05 UTC, raiyni commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +        drawRecipe(graphics2D, potion, 1, 13, Color.BLACK); // Drop shadow
https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/itemidentification/ItemIdentificationOverlay.java

2024-10-28 21:13 UTC, whiitehead commented
Been busy with work and life. Finally got to updating the PR

2024-10-29 01:55 UTC, raiyni requested changes

2024-10-29 01:55 UTC, raiyni commented on src/main/java/work/fking/masteringmixology/MasteringMixologyConfig.java
> +    default InventoryPotionTagType inventoryPotionTagType() {
This review is still valid, you can reuse the current method and key. The value will be invalidated for users and made the proper type.

https://github.com/hex-agon/mastering-mixology/pull/78/files#diff-b31dc957ab0834a1c3e501887b017cd26479a0f69deaa394d962feb653e6f82aL71

2024-10-29 01:55 UTC, raiyni commented on src/main/java/work/fking/masteringmixology/MasteringMixologyPlugin.java
> +            var potionType = PotionType.fromItemId(item.getId(), false);
Not sure I really care for this style of having a flagged return filter for the function. I think it makes more sense to check `potionType.modifiedItemId() == item.getId()` in the below continue.

2024-10-29 05:18 UTC, whiitehead commented on src/main/java/work/fking/masteringmixology/InventoryPotionOverlay.java
> +        drawRecipe(graphics2D, potion, 1, 13, Color.BLACK); // Drop shadow
I can change it to do it this way but I don't think it makes much difference at this point. After making those other changes, the text rendering has gotten pretty simple.

2024-10-30 01:00 UTC, raiyni approved these changes
Think this looks good, thank you

2024-10-30 06:39 UTC, BlueSoapTurtle commented
LGTM 👍

2024-10-30 13:46 UTC, merged